  services:
    - type: web
      name: vc-workflow-web
      env: python3
      startCommand: "gunicorn app:app"
      buildCommand: "pip install -r requirements.txt"
      healthCheckPath: "/api/test"

    - type: worker
      name: vc-workflow-worker
      env: python3
      startCommand: "python worker.py"
      buildCommand: "pip install -r requirements.txt"
